name: Upload release artifacts

on:
  release:
    types: [published]

env:
  QTWEBKIT_BUILD_NUMBER: 1583342509
  QTWEBKIT_BRANCH: 5.212
  QTWEBKIT_DOWNLOAD_ROOT: "http://download.qt.io/snapshots/ci/qtwebkit"
  QTWEBKIT_SNAPSHOTS_REPO: "https://code.qt.io/cgit/qt/qtwebkit.git"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download QtWebKit artifacts
      id: qtwebkit_artifacts
      run: |
        download_qtwebkit_dir() {
          wget -r -np -nH --cut-dirs="$1" --reject="index.html*,*.mirrorlist" "${QTWEBKIT_DOWNLOAD_ROOT}/${QTWEBKIT_BRANCH}/${QTWEBKIT_BUILD_NUMBER}/$2/"
        }
        download_qtwebkit_dir 6 qtwebkit
        download_qtwebkit_dir 7 src/submodules
        download_qtwebkit_dir 6 debug_information

    - name: Verify snapshot tag
      run: |
        snapshot_sha1=$(cat SHA1)
        pwd -P
        git clone --depth 1 "$QTWEBKIT_DOWNLOAD_ROOT" qtwebkit-snapshots
        cd qtwebkit-snapshots
        original_sha1=$(git log -n1 $snapshot_sha1 | awk '/\s+Import QtWebKit commit [0-9a-f]+$/ {print $NF}')
        #original_tag=$(git describe $original_sha1)
        #echo "Snapshot commit: $snapshot_sha1 Original commit: $original_tag ( $original_sha1 )"
        echo "Snapshot commit: $snapshot_sha1 Original commit: $original_sha1"
        echo "github.ref = ${{ github.ref }}"
        pwd -P

    - name: Stupid test
      run: pwd -P

    - name: Upload files to a GitHub release
      uses: csexton/release-asset-action@v2
      with:
        pattern: "*.7z"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
